import random
import time
def gen_random_emoticon_face():
	p6 = random.choice("_<=" "\-")
	p1 = random.choice("{:/[" "<|(")
	p2 = random.choice("*'`" "^!")
	p3 = random.choice("_o.~v" "w#0-c")
	p4 = random.choice("*`'" "^!")
	p5 = random.choice(")\|" "}>]")
	p7 = random.choice("_=3" "/:->")
	print(p6 + p1 + p2 + p3 + p4 + p5 + p7)

print("__________['']")
print("|||||||||||``  =('o') =<'0'> ")


gen_random_emoticon_face()
time.sleep(.01)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.0555)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()
time.sleep(.05)
gen_random_emoticon_face()


print("   M   ")
time.sleep(.15)
print("  / \ ")
time.sleep(.15)
print(" |' '| ")
time.sleep(.15)
print(" \   /")
time.sleep(.15)
print("  |  |")
time.sleep(.15)
print(" |  |")
time.sleep(.15)
print("|  |")
time.sleep(.15)
print("|  |")
time.sleep(.15)
print("|  |")
time.sleep(.15)
print(" |  |")
time.sleep(.15)
print("  |  |")
time.sleep(.15)
print("  |  |")
time.sleep(.15)
print("  |  |")
time.sleep(.15)
print(" |  |")
time.sleep(.15)
print("|  |")
time.sleep(.15)
print("|  |")
time.sleep(.15)
print("|  |")
time.sleep(.15)
print(" |  |")
time.sleep(.15)
print("  |  |")
time.sleep(.15)
print("  |  |")
time.sleep(.15)
print("  |  |")
time.sleep(.15)
print(" |  |")
time.sleep(.15)
print("|  |")
time.sleep(.15)
print("|  |")
time.sleep(.15)
print("|  |")
time.sleep(.15)
print(" |  |")
time.sleep(.15)
print("  |  |")
time.sleep(.15)
print("  |  |")
time.sleep(.15)
print("  |  |")
time.sleep(.15)
print(" |  |")
time.sleep(.15)
print("|  |")
time.sleep(.15)
print("|  |")
time.sleep(.15)
print("|  |")
time.sleep(.15)
print(" |  |")
time.sleep(.15)
print("  |  |")
time.sleep(.15)
print("  |  |")
time.sleep(.15)
print("  |  |")
time.sleep(.15)
print(" |  |")
print("|  |")
time.sleep(.15)
print("|  |")
time.sleep(.15)
print("|  |")
time.sleep(.15)
print(" |  |")
time.sleep(.15)
print("  |  |")
time.sleep(.15)
print("  |  |")
time.sleep(.15)
print("  |  |")
time.sleep(.15)
print(" |  |")
time.sleep(.15)
print(" \  / ")
time.sleep(.15)
print("  \/ ")


print("")